# Generated by Django 4.2.1 on 2023-06-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
